#!/bin/bash

# docker
if [ -f /etc/scc/.dkr-bashrc ]; then
  source /etc/scc/.dkr-bashrc
fi

# docker-compose
if [ -f /etc/scc/.doco-bashrc ]; then
  source /etc/scc/.doco-bashrc
fi

# git
if [ -f /etc/scc/.git-bashrc ]; then
  source /etc/scc/.git-bashrc
fi

# tmux
if [ -f /etc/scc/.tmx-bashrc ]; then
  source /etc/scc/.tmx-bashrc
fi

# kubernetes and minikube
if [ -f /etc/scc/.k8s-bashrc ]; then
  source /etc/scc/.k8s-bashrc
fi
