#!/bin/bash

tee /etc/scc/.dc-bashrc > /dev/null << 'EOF'
#!/bin/bash

# NGINX functions
dc-nginx-reset() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
dc-nginx-down() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
}
dc-nginx-up() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
dc-nginx-logs() {
  docker logs nginx -f
}

# SQLSERVER functions
dc-sqlserver-reset() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
dc-sqlserver-down() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
}
dc-sqlserver-up() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
dc-sqlserver-logs() {
  docker logs sqlserver2022 -f
}

# NEXUS functions
dc-nexus-reset() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
dc-nexus-down() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
}
dc-nexus-up() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
dc-nexus-logs() {
  docker logs nexus -f
}

# JENKINS functions
dc-jenkins-reset() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
dc-jenkins-down() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
}
dc-jenkins-up() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
dc-jenkins-logs() {
  docker logs jenkins -f
}

# GITLAB functions
dc-gitlab-reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
dc-gitlab-down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
}
dc-gitlab-up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
dc-gitlab-logs() {
  docker logs gitlab -f
}

# jira functions
dc-jira-reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
dc-jira-down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
}
dc-jira-up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
dc-jira-logs() {
  docker logs jira -f
}

# postgres17 functions for gitlab
dc-postgres17-reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
dc-postgres17-down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
}
dc-postgres17-up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
dc-postgres17-logs() {
  docker logs gitlab-postgresql -f
}

# postgres15 functions for jira
dc-postgresql-reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
dc-postgres15-down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
}
dc-postgres15-up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
dc-postgres15-logs() {
  docker logs jira-postgresql -f
}

# redis functions
dc-redis-reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
dc-redis-down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
}
dc-redis-up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
dc-redis-logs() {
  docker logs redis -f
}

# middleweb-backend functions
dc-middleweb-backend-reset() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d
}
dc-middleweb-backend-down() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down
}
dc-middleweb-backend-up() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d
}
dc-middleweb-backend-logs() {
  docker logs middleweb-backend -f
}

# middleweb-frontend functions
dc-middleweb-frontend-reset() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml down
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml up --force-recreate -d
}
dc-middleweb-frontend-down() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml down
}
dc-middleweb-frontend-up() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml up --force-recreate -d
}
dc-middleweb-frontend-logs() {
  docker logs middleweb-frontend -f
}

# ALL functions
dc-all-down() {
  bash /etc/scc//dc-all-down.sh
}
dc-all-up() {
  bash /etc/scc//dc-all-up.sh
}
dc-all-reset() {
  dc-all-down
  dc-all-up
}

# Docker ps shortcuts
function dps { docker ps; }
function dpsa { docker ps -a; }
function dpss { docker ps --format "table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"; }
function wdps { watch -e docker ps; }
function wdpss { watch -e "docker ps --format 'table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}'"; }

# Docker system management
function dstats { docker stats; }
function dvolumes { docker volume ls; }
function dnetworks { docker network ls; }
function dclean { docker system prune -af; }
function dimages { docker image ls; }

# Container exec shortcuts
function dex-nginx { docker exec -it nginx bash; }
function dex-gitlab { docker exec -it gitlab bash; }
function dex-jenkins { docker exec -it jenkins bash; }
function dex-nexus { docker exec -it nexus bash; }
function dex-sqlserver { docker exec -it sqlserver2022 bash; }
function dex-jira { docker exec -it jira bash; }
function dex-postgres15 { docker exec -it jira-postgresql bash; }
function dex-postgres17 { docker exec -it gitlab-postgresql bash; }
function dex-redis { docker exec -it redis bash; }
function dex-middleweb-backend { docker exec -it middleweb-backend bash; }
function dex-middleweb-frontend { docker exec -it middleweb-frontend bash; }

# Container logs shortcuts
function dlogs-nginx { docker logs nginx -f; }
function dlogs-gitlab { docker logs gitlab -f; }
function dlogs-jenkins { docker logs jenkins -f; }
function dlogs-nexus { docker logs nexus -f; }
function dlogs-sqlserver { docker logs sqlserver2022 -f; }
function dlogs-jira { docker logs jira -f; }
function dlogs-postgres15 { docker logs postgresql -f; }
function dlogs-postgres17 { docker logs postgresql -f; }
function dlogs-redis { docker logs redis -f; }
function dlogs-middleweb-backend { docker logs middleweb-backend -f; }
function dlogs-middleweb-frontend { docker logs middleweb-frontend -f; }

# Environment variables
export p-confd=/opt/docker/nginx/conf.d/
export p-nginx=/opt/docker/nginx/
export p-nexus=/opt/docker/nexus/
export p-jenkins=/opt/docker/jenkins/
export p-gitlab=/opt/docker/gitlab/
export p-jira=/opt/docker/jira/
export p-sqlserver=/opt/docker/sqlserver/
export p-middleweb-backend=/home/jenkins/jobs/compose/middleweb-backend.yml
export p-middleweb-frontend=/home/jenkins/jobs/compose/middleweb-frontend.yml

# Directory shortcuts
function cd-confd { cd /opt/docker/nginx/conf.d/; }
function cd-nginx { cd /opt/docker/nginx/; }
function cd-redis { cd /opt/docker/redis/; }
function cd-postgresql { cd /opt/docker/postgresql/; }
function cd-gitlab { cd /opt/docker/gitlab/; }
function cd-nexus { cd /opt/docker/nexus/; }
function cd-jenkins { cd /opt/docker/jenkins/; }
function cd-sqlserver { cd /opt/docker/sqlserver/; }
function cd-jobs { cd /home/jenkins/jobs/; }
function cd-jira { cd /opt/docker/jira/; }
function cd-middleweb-backend { cd /home/jenkins/jobs/middleweb-backend/; }
function cd-middleweb-frontend { cd /home/jenkins/jobs/middleweb-frontend/; }

# Docker compose shortcuts
function dc-build { docker compose build; }
function dc-up { docker compose up -d; }
function dc-down { docker compose down; }
function dc-restart { docker compose restart; }
function dc-logs { docker compose logs -f; }
function dc-ps { docker compose ps; }

EOF

tee /etc/scc//dc-all-down.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down

docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
EOF

tee /etc/scc//dc-all-up.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d

docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
EOF


tee /etc/scc//dc-nginx-up.sh > /dev/null << 'EOF'
#!/bin/bash

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
EOF

