#!/bin/bash

tee /etc/scc/.dc_bashrc > /dev/null << 'EOF'
#!/bin/bash

# Docker compose shortcuts
function dc_up { docker compose up -f "$1" -d; }
function dc_down { docker compose -f "$1" down; }

function dc_restart() { 
    docker compose -f "$1" down; 
    docker compose -f "$1" up; -d 
}
function dc_reset() { 
    docker compose -f "$1" down; 
    docker compose -f "$1" up --force-recreate -d; 
}

# NGINX functions
dc_nginx_reset() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
dc_nginx_down() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
}
dc_nginx_up() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
dc_nginx_logs() {
  docker logs nginx -f
}

# SQLSERVER functions
dc_sqlserver_reset() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
dc_sqlserver_down() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
}
dc_sqlserver_up() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
dc_sqlserver_logs() {
  docker logs sqlserver2022 -f
}

# NEXUS functions
dc_nexus_reset() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
dc_nexus_down() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
}
dc_nexus_up() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
dc_nexus_logs() {
  docker logs nexus -f
}

# JENKINS functions
dc_jenkins_reset() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
dc_jenkins_down() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
}
dc_jenkins_up() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
dc_jenkins_logs() {
  docker logs jenkins -f
}

# GITLAB functions
dc_gitlab_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
dc_gitlab_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
}
dc_gitlab_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
dc_gitlab_logs() {
  docker logs gitlab -f
}

# jira functions
dc_jira_reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
dc_jira_down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
}
dc_jira_up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
dc_jira_logs() {
  docker logs jira -f
}

# postgres17 functions for gitlab
dc_postgres17_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
dc_postgres17_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
}
dc_postgres17_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
dc_postgres17_logs() {
  docker logs gitlab-postgresql -f
}

# postgres15 functions for jira
dc_postgresql_reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
dc_postgres15_down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
}
dc_postgres15_up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
dc_postgres15_logs() {
  docker logs jira-postgresql -f
}

# redis functions
dc_redis_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
dc_redis_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
}
dc_redis_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
dc_redis_logs() {
  docker logs redis -f
}

# ALL functions
dc_all_down() {
  bash /etc/scc//dc_all_down.sh
}
dc_all_up() {
  bash /etc/scc//dc_all_up.sh
}
dc_all_reset() {
  dc_all_down
  dc_all_up
}

# Docker ps shortcuts
function dps { docker ps; }
function dpsa { docker ps -a; }
function dpss { docker ps --format "table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"; }
function wdps { watch -e docker ps; }
function wdpss { watch -e "docker ps --format 'table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}'"; }

# Docker system management
function dstats { docker stats; }
function dvolumes { docker volume ls; }
function dnetworks { docker network ls; }
function dclean { docker system prune -af; }
function dimages { docker image ls; }

# Container exec shortcuts
function dex_nginx { docker exec -it nginx bash; }
function dex_gitlab { docker exec -it gitlab bash; }
function dex_jenkins { docker exec -it jenkins bash; }
function dex_nexus { docker exec -it nexus bash; }
function dex_sqlserver { docker exec -it sqlserver2022 bash; }
function dex_jira { docker exec -it jira bash; }
function dex_postgres15 { docker exec -it jira-postgresql bash; }
function dex_postgres17 { docker exec -it gitlab-postgresql bash; }
function dex_redis { docker exec -it redis bash; }

# Container logs shortcuts
function dlgs_nginx { docker logs nginx -f; }
function dlgs_gitlab { docker logs gitlab -f; }
function dlgs_jenkins { docker logs jenkins -f; }
function dlgs_nexus { docker logs nexus -f; }
function dlgs_sqlserver { docker logs sqlserver2022 -f; }
function dlgs_jira { docker logs jira -f; }
function dlgs_postgres15 { docker logs postgresql -f; }
function dlgs_postgres17 { docker logs postgresql -f; }
function dlgs_redis { docker logs redis -f; }

# Environment variables
export p_confd=/opt/docker/nginx/conf.d/
export p_nginx=/opt/docker/nginx/
export p_nexus=/opt/docker/nexus/
export p_jenkins=/opt/docker/jenkins/
export p_gitlab=/opt/docker/gitlab/
export p_jira=/opt/docker/jira/
export p_sqlserver=/opt/docker/sqlserver/

# Directory shortcuts
function cd_confd { cd /opt/docker/nginx/conf.d/; }
function cd_nginx { cd /opt/docker/nginx/; }
function cd_redis { cd /opt/docker/redis/; }
function cd_postgresql { cd /opt/docker/postgresql/; }
function cd_gitlab { cd /opt/docker/gitlab/; }
function cd_nexus { cd /opt/docker/nexus/; }
function cd_jenkins { cd /opt/docker/jenkins/; }
function cd_sqlserver { cd /opt/docker/sqlserver/; }
function cd_jobs { cd /home/jenkins/jobs/; }
function cd_jira { cd /opt/docker/jira/; }

# Docker compose shortcuts
function dc_build { docker compose build; }
function dc_up { docker compose up -d; }
function dc_down { docker compose down; }
function dc_restart { docker compose restart; }
function dc_logs { docker compose logs -f; }
function dc_ps { docker compose ps; }

EOF

tee /etc/scc//dc_all_down.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
EOF

tee /etc/scc//dc_all_up.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
EOF

