#!/bin/bash

tee /etc/scc/.dkr_bashrc > /dev/null << 'EOF'
#!/bin/bash

# Docker monitor shortcuts
function dps { docker ps; }
function dpsa { docker ps -a; }
function dpss { docker ps --format "table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"; }
function wdps { watch -e docker ps; }
function wdpss { watch -e "docker ps --format 'table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}'"; }

# Docker system management
function dstats { docker stats; }
function dvolumes { docker volume ls; }
function dnetworks { docker network ls; }
function dclean { docker system prune -af; }
function dimages { docker image ls; }

function dbild { docker build .; }
function dlgs { docker logs "$1" -f; }

EOF
