#!/bin/bash

tee /etc/scc/.dkr-bashrc > /dev/null << 'EOF'
#!/bin/bash

# Docker ps shortcuts
function dps { docker ps; }
function dpsa { docker ps -a; }
function dpss { docker ps --format "table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"; }
function wdps { watch -e docker ps; }
function wdpss { watch -e "docker ps --format 'table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}'"; }

# Docker system management
function dstats { docker stats; }
function dvolumes { docker volume ls; }
function dnetworks { docker network ls; }
function dclean { docker system prune -af; }
function dimages { docker image ls; }

function dbuild { docker build .; }
function dc-logs { docker logs "$1" -f; }

# Docker compose shortcuts
function dc-up { docker compose up -f "$1" -d; }
function dc-down { docker compose -f "$1" down; }
function dc-restart() { 
    docker compose -f "$1" down; 
    docker compose -f "$1" up; -d 
}
function dc-reset() { 
    docker compose -f "$1" down; 
    docker compose -f "$1" up --force-recreate -d; 
}

EOF
