#!/bin/bash

tee /etc/scc/.doco_bashrc > /dev/null << 'EOF'
#!/bin/bash

# NGINX functions
doco_nginx_reset() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
doco_nginx_down() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
}
doco_nginx_up() {
  docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
}
doco_nginx_logs() {
  docker logs nginx -f
}

# SQLSERVER functions
doco_sqlserver_reset() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
doco_sqlserver_down() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
}
doco_sqlserver_up() {
  docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
}
doco_sqlserver_logs() {
  docker logs sqlserver2022 -f
}

# NEXUS functions
doco_nexus_reset() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
doco_nexus_down() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
}
doco_nexus_up() {
  docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
}
doco_nexus_logs() {
  docker logs nexus -f
}

# JENKINS functions
doco_jenkins_reset() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
doco_jenkins_down() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down
}
doco_jenkins_up() {
  docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d
}
doco_jenkins_logs() {
  docker logs jenkins -f
}

# GITLAB functions
doco_gitlab_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
doco_gitlab_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
}
doco_gitlab_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d
}
doco_gitlab_logs() {
  docker logs gitlab -f
}

# jira functions
doco_jira_reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
doco_jira_down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml down
}
doco_jira_up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/jira-compose.yml up --force-recreate -d
}
doco_jira_logs() {
  docker logs jira -f
}

# postgres17 functions for gitlab
doco_postgres17_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
doco_postgres17_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
}
doco_postgres17_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
}
doco_postgres17_logs() {
  docker logs gitlab-postgresql -f
}

# postgres15 functions for jira
doco_postgresql_reset() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
doco_postgres15_down() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml down
}
doco_postgres15_up() {
  docker compose --env-file /opt/docker/jira/.env -f /opt/docker/jira/postgresql-compose.yml up --force-recreate -d
}
doco_postgres15_logs() {
  docker logs jira-postgresql -f
}

# redis functions
doco_redis_reset() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
doco_redis_down() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down
}
doco_redis_up() {
  docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
}
doco_redis_logs() {
  docker logs redis -f
}

# middleweb-backend functions
doco_middleweb-backend_reset() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d
}
doco_middleweb-backend_down() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down
}
doco_middleweb-backend_up() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d
}
doco_middleweb-backend_logs() {
  docker logs middleweb-backend -f
}

# middleweb-frontend functions
doco_middleweb-frontend_reset() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml down
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml up --force-recreate -d
}
doco_middleweb-frontend_down() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml down
}
doco_middleweb-frontend_up() {
  docker compose -f /home/jenkins/jobs/compose/middleweb-frontend.yml up --force-recreate -d
}
doco_middleweb-frontend_logs() {
  docker logs middleweb-frontend -f
}

# ALL functions
doco_all_down() {
  bash /etc/scc//doco_all_down.sh
}
doco_all_up() {
  bash /etc/scc//doco_all_up.sh
}
doco_all_reset() {
  doco_all_down
  doco_all_up
}

# Docker ps shortcuts
function dps { docker ps; }
function dpsa { docker ps -a; }
function dpss { docker ps --format "table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}"; }
function wdps { watch -e docker ps; }
function wdpss { watch -e "docker ps --format 'table {{.ID}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}\t{{.Networks}}'"; }

# Docker system management
function dstats { docker stats; }
function dvolumes { docker volume ls; }
function dnetworks { docker network ls; }
function dclean { docker system prune -af; }
function dimages { docker image ls; }

# Container exec shortcuts
function dex_nginx { docker exec -it nginx bash; }
function dex_gitlab { docker exec -it gitlab bash; }
function dex_jenkins { docker exec -it jenkins bash; }
function dex_nexus { docker exec -it nexus bash; }
function dex_sqlserver { docker exec -it sqlserver2022 bash; }
function dex_jira { docker exec -it jira bash; }
function dex_postgres15 { docker exec -it jira-postgresql bash; }
function dex_postgres17 { docker exec -it gitlab-postgresql bash; }
function dex_redis { docker exec -it redis bash; }
function dex_middleweb-backend { docker exec -it middleweb-backend bash; }
function dex_middleweb-frontend { docker exec -it middleweb-frontend bash; }

# Container logs shortcuts
function dlogs_nginx { docker logs nginx -f; }
function dlogs_gitlab { docker logs gitlab -f; }
function dlogs_jenkins { docker logs jenkins -f; }
function dlogs_nexus { docker logs nexus -f; }
function dlogs_sqlserver { docker logs sqlserver2022 -f; }
function dlogs_jira { docker logs jira -f; }
function dlogs_postgres15 { docker logs postgresql -f; }
function dlogs_postgres17 { docker logs postgresql -f; }
function dlogs_redis { docker logs redis -f; }
function dlogs_middleweb-backend { docker logs middleweb-backend -f; }
function dlogs_middleweb-frontend { docker logs middleweb-frontend -f; }

# Environment variables
export p_confd=/opt/docker/nginx/conf.d/
export p_nginx=/opt/docker/nginx/
export p_nexus=/opt/docker/nexus/
export p_jenkins=/opt/docker/jenkins/
export p_gitlab=/opt/docker/gitlab/
export p_jira=/opt/docker/jira/
export p_sqlserver=/opt/docker/sqlserver/
export p_middleweb_backend=/home/jenkins/jobs/compose/middleweb-backend.yml
export p_middleweb_frontend=/home/jenkins/jobs/compose/middleweb-frontend.yml

# Directory shortcuts
function cd_confd { cd /opt/docker/nginx/conf.d/; }
function cd_nginx { cd /opt/docker/nginx/; }
function cd_redis { cd /opt/docker/redis/; }
function cd_postgresql { cd /opt/docker/postgresql/; }
function cd_gitlab { cd /opt/docker/gitlab/; }
function cd_nexus { cd /opt/docker/nexus/; }
function cd_jenkins { cd /opt/docker/jenkins/; }
function cd_sqlserver { cd /opt/docker/sqlserver/; }
function cd_jobs { cd /home/jenkins/jobs/; }
function cd_jira { cd /opt/docker/jira/; }
function cd_middleweb-backend { cd /home/jenkins/jobs/middleweb-backend/; }
function cd_middleweb-frontend { cd /home/jenkins/jobs/middleweb-frontend/; }

# Docker compose shortcuts
function dc_build { docker compose build; }
function dc_up { docker compose up -d; }
function dc_down { docker compose down; }
function dc_restart { docker compose restart; }
function dc_logs { docker compose logs -f; }
function dc_ps { docker compose ps; }

EOF

tee /etc/scc//doco_all_down.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml down
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml down

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml down
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml down
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml down

docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml down

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml down
EOF

tee /etc/scc//doco_all_up.sh > /dev/null << 'EOF'
#!/bin/bash

docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/postgresql-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/redis-compose.yml up --force-recreate -d
docker compose --env-file /opt/docker/gitlab/.env -f /opt/docker/gitlab/gitlab-compose.yml up --force-recreate -d

docker compose -f /home/jenkins/jobs/compose/middleweb-backend.yml up --force-recreate -d

docker-compose -f /opt/docker/nexus/nexus-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/sqlserver/sqlserver-docker-compose.yml up --force-recreate -d
docker-compose -f /opt/docker/jenkins/jenkins-docker-compose.yml up --force-recreate -d

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
EOF


tee /etc/scc//doco_nginx_up.sh > /dev/null << 'EOF'
#!/bin/bash

docker-compose -f /opt/docker/nginx/nginx-docker-compose.yml up --force-recreate -d
EOF

