#!/bin/bash

tee /etc/scc/.git-bashrc > /dev/null << 'EOF'
#!/bin/bash

# Git shortcuts
function gs { git status; }
function ga { git add .; }
function gc { git commit -m "$1"; }
function gp { git push; }
function gpl { git pull; }
function gco { git checkout "$1"; }
function gb { git branch; }

EOF
